### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by casconed** [UseAllFive/ua5AdminThemePlugin#3]
web/ua5_2/dependencies/wysihtml5/dist/wysihtml5-0.3.0.js seems to be missing from the plugin, resulting in the following error when used in Kneon:

`Action "ua5AdminThemePlugin/ua5_2" does not exist.`

**Comment by m14t** [comment]
This is likely a dependency error, that was handled previously with an SVN external.

https://github.com/xing/wysihtml5/tree/0.3.0
